# <span style="color:YellowGreen">Akanksha Kisan Shivale</span>
# <span style="color:YellowGreen">23092002  </span>
# <span style="color:YellowGreen"> IMCA 1st</span>

# <span style="color:teal"><h2>Q2. Row Echelon Form: 
</h2></span>

In [7]:
import numpy as np

def ref(matrix):
    mat = matrix.copy().astype(float)
    rows, cols = mat.shape

    row_idx = 0
    for col_idx in range(cols):
        if row_idx >= rows:
            break

        max_row = np.argmax(np.abs(mat[row_idx:, col_idx])) + row_idx
        
        if mat[max_row, col_idx] == 0:
            continue

        mat[[row_idx, max_row]] = mat[[max_row, row_idx]]
        mat[row_idx] = mat[row_idx] / mat[row_idx, col_idx]

        for r in range(row_idx + 1, rows):
            mat[r] = mat[r] - mat[r, col_idx] * mat[row_idx]

        row_idx += 1

    return mat

# Set the random seed
np.random.seed(2)

# Generate a 5x5 matrix with random integers between 0 and 9
A = np.random.randint(0, 10, (5, 5))
print("Original Matrix A:")
print(A)

# Calculate the Row Echelon Form of the matrix A
REF_A = ref(A)
print("Row Echelon Form of Matrix A:")
print(REF_A)


Original Matrix A:
[[8 8 6 2 8]
 [7 2 1 5 4]
 [4 5 7 3 6]
 [4 3 7 6 1]
 [3 5 8 4 6]]
Row Echelon Form of Matrix A:
[[ 1.          1.          0.75        0.25        1.        ]
 [-0.          1.          0.85       -0.65        0.6       ]
 [ 0.          0.          1.          0.89690722 -0.49484536]
 [ 0.          0.          0.          1.          4.14606742]
 [ 0.          0.          0.          0.          1.        ]]
